# Site settings
title: Jerven Clark  Chua
description: >-
  A personal blog of what I generally find interesting - snippets, new tech, memes and so on.
lang: en-US
timezone: Asia/Manila
image: assets/img/avatar.jpeg # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/jervenclark/jervenclark.github.io
mode: dark

# Profile settings
author:
  name: Jerven Clark Chua
  bio: >-
    I am Jerven Clark Chua: a software developer and data science enthusiast.
  username: jervenclark
  email: jervenclark.chua@gmail.com
  avatar: /assets/img/avatar.jpeg

# Url settings
url: "https://jervenclarkchua.com"
# baseurl: "https://jervenclarkchua.com"
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    series:
    description:
    archived: false
    usemathjax: false
  draft_default_front_matter:
    modified:
    tags: []
    series:
    description:
    archived: false
    usemathjax: false

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - vendor
  - _posts/template.md
  - artifacts

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
